# Generated by Django 5.0.6 on 2024-05-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [("can_eat_pizzas", "Can eat pizzas")],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[],
            options={
                "permissions": [("can_deliver_pizzas", "Can deliver pizzas")],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.person",),
        ),
    ]
